### ISSUE TITLE
rules prohibit new table data rows to retrieve id of freshly-created document

### ISSUE THREAD

**Issue by TCashion** [TCashion/TCashion.github.io#9]
Gives this error: 
error.ts:166 Uncaught (in promise) FirebaseError: Missing or insufficient permissions.
    at new Hr (https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:48219)
    at sf.fromRpcStatus (https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:250751)
    at sf.fromWatchChange (https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:260267)
    at zh.onMessage (https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:214276)
    at https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:212991
    at https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:213779
    at https://www.gstatic.com/firebasejs/7.8.0/firebase-firestore.js:1:62333
Hr @ error.ts:166
sf.fromRpcStatus @ serializer.ts:162
sf.fromWatchChange @ serializer.ts:724
zh.onMessage @ persistent_stream.ts:559
(anonymous) @ persistent_stream.ts:442
(anonymous) @ persistent_stream.ts:492
(anonymous) @ async_queue.ts:285
Promise.then (async)
stopClock @ app.js:296
(anonymous) @ app.js:222
dispatch @ jquery-3.4.1.min.js:2
v.handle @ jquery-3.4.1.min.js:2

**Comment by TCashion** [comment]
I think it has something to do with the get permission

**Comment by TCashion** [comment]
this problem is caused by this part of the rules: 
// && request.auth.uid == resource.data.userID;  // commented out because this doesn't allow realtime capture of current data id

**Comment by TCashion** [comment]
> this problem is caused by this part of the rules:
> // && request.auth.uid == resource.data.userID; // commented out because this doesn't allow realtime capture of current data id

by leaving this disabled for now, only authenticated users can read data, but they can still read data that is not connected to their own uid. need to resolve this somehow...

**Comment by TCashion** [comment]
workaround is to not have user email addresses in the data logs. This, in combination with only allowing data registries from the url, plus the other security rules, would prevent any user from seeing other users' email addresses.
